platforms: use appended DTB for dragonboard fastboot
dragonboard-410c and dragonboard-820c use the LK bootloader which
requires the DTB appended to the kernel image, same as sm8350-hdk.
Their LAVA jobs currently fail with:

  ERROR: Bad magic in device tree table
  DTB offset is incorrect, kernel image does not have appended DTB

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>