scheduler-cip: Revert removing collabora platforms from cip config
Removing runtime broke KernelCI staging
```
TypeError: SchedulerEntry.__init__() missing 1 required positional argument: 'runtime'
```

Signed-off-by: Arisu Tachibana <arisu.tachibana@miraclelinux.com>