src/send_kcidb: fix `_run` with `APIHelper`
Fix below error as the method renamed to `receive_event_node`
as per the `APIHelper` implementation.
`AttributeError: 'APIHelper' object has no attribute 'receive_node_event'`

Signed-off-by: JenySadadia <jeny.sadadia@collabora.com>